### ISSUE TITLE
Show warning when editing the mappings

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/WikibaseRDF#115]
> a warning to pop up to users when they try to edit / delete a property mapping. The warning should say: “Please be advised that after editing or deleting property mappings, a reset of the triplestore is recommended in order to clear the outdated mappings.”

Probably we can show it right in the UI as soon as the user goes into edit mode for the mappings.

**Comment by malberts** [comment]
Should we add a message directly in the page, or does this need to be a popup? The latter would require some acknowledgement (maybe just closing, doesn't have to be Yes/No).

And some additional over-thinking if we use a direct message:
* adding it above the mappings table is going to make the whole page jump down
* adding it to the bottom of the table might not be visible
* we'll probably have to inject it somewhere in the specific row/mapping. This is also going to make everything below jump down

And finally, should this message show/pop up on every edit? Only first edit on a page? Should a user be able to acknowledge and then permanently hide it?

**Comment by lozanaross** [comment]
First - just important to point out this needs to only apply to properties (not items). 

Second, I was thinking maybe we can just reuse the native style of pop ups already available in Wikibase, e.g. this: 
![Screenshot 2022-11-09 at 17 00 59](https://user-images.githubusercontent.com/25489750/200880128-9b3bcaa4-c646-4765-bdee-b9e8f85b3dbe.png)

Ideally the pop up comes up after an initial mapping is created and only when a user starts trying to edit it, but this may be trickier to implement than a pop up that's always there, so looking at the existing popup (the one above), we can take inspiration from the text there and say something like:

"By clicking "save" you are creating a permanent statement in the triplestore. Please be advised that any subsequent edits or deletions of property mappings will require a reset of the triplestore in order to clear outdated mappings. This does not apply to item mappings.

Do not show this message again."

I think it will be fine to attach this to the "save" button and allow users to click the "Do not show..." themselves if they want to.

**Comment by JeroenDeDauw** [comment]
![image](https://user-images.githubusercontent.com/146040/201700186-387b66d2-fb69-4bcd-ae56-e857c535557d.png)
