### ISSUE TITLE
Add PHP service to save and retrieve the mappings for an Entity

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/WikibaseRDF#6]
AC:

* Save method
    * Takes an EntityID and all the mapping for that entity
    * Saves the mappings in a slot, in a new revision
* Retrieval method
    * Takes an EntityID
    * Returns the mappings by getting them from a slot in the revision. Or an empty list if there is no data there yet.
* Integration tested
    * automated test that does the save, and then does retrieval to see that the new revision has the new mappings
* Tests (maybe unit) for 
    * retrieving from an entity without mappings
    * retrieving from non existing entity
    * saving to non existing entity 

TBD: Do we want an object to represent the mappings in PHP?

TBD: JSON format for storing the mappings

**Comment by hexmode** [comment]
Looking at [instance of (P31)](https://www.wikidata.org/wiki/Property:P31) (on wikidata.org), I see "rdf:type" is stored as an alias.

Similarly, [subclass of (P15)](https://artbase.rhizome.org/wiki/Property:P15) (on artbase.rhizome.org) has an alias of "rdfs:subClassOf" which is specifically mentioned in [the requirements doc](https://notepad.rhizome.org/wbsg-rdf-extension-workplan-r2) as the mapping:
```
wdt:P15 owl:sameAs rdfs:subClassOf .
```

Because of this, it seems like the user experience is such that if a user provides an alias that is an RDF vocabulary item, that should be used to assist the map creation in some manner. Places where the alias that is RDF vocabulary but does not match the mapping should probably be highlighted, as well.

**Comment by JeroenDeDauw** [comment]
That seems unrelated to this ticket. There also is no requirement to look at aliases. Let's first get the clients requirements out of the way.

**Comment by JeroenDeDauw** [comment]
@hexmode regarding your comment at https://github.com/ProfessionalWiki/WikibaseRDF/pull/10#issuecomment-1146895273:

We can potentially insert something into the JSON returned and received by Wikibase API modules. I'm not sure. Bit of a moot point since that gets turned into the PHP Wikibase DataModel, before it gets serialized again, and persisted. So we cannot just insert extra information in there.

**Comment by hexmode** [comment]
Ok, "moot point" is kind of what I suggested when I said "Or maybe slots could be used as the backing for the mapping key."
