### ISSUE TITLE
Make allowed RDF predicates configurable via wiki page

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/WikibaseRDF#71]
AC:

* `wgWikibaseRdfPredicates` gets merged together with a list defined on a wiki page
* Retrieval happens via a new interface. The implementation does the merge, and perhaps also caching

Example of a config page: https://automated.wikibase.wiki/wiki/MediaWiki:AutomatedValues (see RulesLookup classes https://github.com/ProfessionalWiki/AutomatedValues/tree/master/src/DataAccess)

We could go with a simple wikitext page, where each non-empty line is a value. Perhaps called `MediaWiki:MappingPredicates`

**Comment by JeroenDeDauw** [comment]
Blocks demo's on the demo wiki: https://github.com/ProfessionalWiki/WikibaseRDF/issues/18

**Comment by malberts** [comment]
Some comments related to (1) on https://github.com/ProfessionalWiki/WikibaseRDF/discussions/36#discussioncomment-3277972

With the new config UI I add a predicate "third:option", then I create a mapping:
![Screenshot_20220809_224821](https://user-images.githubusercontent.com/1428594/183757889-215b6b92-69e1-4873-b7ef-4ba0e0238d77.png)

Then I remove the new predicate from the config UI (current validation doesn't check usage):
![Screenshot_20220809_224903](https://user-images.githubusercontent.com/1428594/183758001-b211d2a2-eada-4cd9-9a9f-346fa29b6518.png)

Going back to the mapping UI, the orignal value is still displayed:
![Screenshot_20220809_224923](https://user-images.githubusercontent.com/1428594/183758050-a7d125d6-2a84-43f9-944c-678ed10bd74e.png)

However, when you edit that one it will be blank because the dropdown value does not exist:
![Screenshot_20220809_224947](https://user-images.githubusercontent.com/1428594/183758125-50bf355e-70fd-4796-9be0-c109e4d3b12e.png)

And saving/removing anything will cause an error:
![Screenshot_20220809_225028](https://user-images.githubusercontent.com/1428594/183758224-bde1e9f9-6372-4a8f-be69-c5c218de0d17.png)
Because we are sending the original value. API response:
![Screenshot_20220809_225054](https://user-images.githubusercontent.com/1428594/183758296-20b5e74c-d69c-4661-a0c2-fc97d31e6f3d.png)

**Comment by JeroenDeDauw** [comment]
Showing a waning, or even blocking save, on the config page, can indeed be nice. It however does not seem needed for the MVP and was not requested by the customer. I think we can start by simply stating that you should not remove in-use predicates. That avoids guesswork about if and when, and to which degree, there would be a problem, and what types of solutions would fit well.
