### ISSUE TITLE
Get revision-specific mappings

### ISSUE THREAD

**Issue by malberts** [ProfessionalWiki/WikibaseRDF#84]
I ran into this while doing #79.

Currently we are always retrieving the latest mappings (i.e. last revision of the slot).

This causes the diff page and a specific revision page to show the wrong mappings.

We'll need to pass in the specific revision here:
https://github.com/ProfessionalWiki/WikibaseRDF/blob/master/src/Persistence/SlotEntityContentRepository.php#L31-L40

Example of a specific revision page that did not have mappings:
![Screenshot_20220813_102042](https://user-images.githubusercontent.com/1428594/184475579-a1eb5bae-1543-4417-9c53-c5844c964a0e.png)

Example of diff page:
![Screenshot_20220813_102122](https://user-images.githubusercontent.com/1428594/184475599-61b42d6b-f133-4c1b-92d5-e721e3b1f7f7.png)

**Comment by JeroenDeDauw** [comment]
Looks like you can get the revision ID in [addMappingUi](https://github.com/ProfessionalWiki/WikibaseRDF/blob/master/src/EntryPoints/MediaWikiHooks.php#L66-L77) via `$page->getRevisionId()`. You can then pass that to the `ContentSlotMappingRepository` constructor so that the `MappingRepository` interface does not need to be changed. Looks like the `ShowMappingsUseCase` could be refactored away in the process.
