### ISSUE TITLE
Determine requirements for mapping listing web API

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/WikibaseRDF#9]
AC:

* Clear requirements in a new task

**Comment by hexmode** [comment]
From reading the RDF specs and such, it looks like these mappings should be exposed via Special:EntityData.

For example, see the turtle format output for P15 (subclassOf) on rhizome.  It contains the following (edited) [fragment](https://artbase.rhizome.org/wiki/Special:EntityData/P15.ttl):
``` turtle
@prefix wd: <https://artbase.rhizome.org/entity/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix wdt: <https://artbase.rhizome.org/prop/direct/> .

wd:P15 rdfs:label "subclass of"@en ;
	wdt:P2 <http://www.wikidata.org/entity/P279>,
		<http://www.w3.org/2000/01/rdf-schema#subClassOf> .
```

Since wdt:P2 is "exact match" (and refers to URLs), this appears to be another instance (in addition to the aliases mentioned in another comment) to try and produce what this project is trying to do.

With this in mind, it looks like the mappings users create with WikibaseRDF should be exposed via Special:EntityData and that output would serve as machine-readable way these mappings are exposed.

If so, then the mapping mentioned at the start of the [specification](https://notepad.rhizome.org/wbsg-rdf-extension-workplan-r2#) (`wdt:P15 owl:sameAs rdfs:subClassOf .`), would automatically add the statement to the turtle output:
``` turtle
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix wdt: <https://artbase.rhizome.org/prop/direct/> .

wdt:P15 owl:sameAs rdfs:subClassOf .
```

**Comment by JeroenDeDauw** [comment]
The task for adding the mappings to the RDF output is https://github.com/ProfessionalWiki/WikibaseRDF/issues/8

You are right that you can access one version of said output via Special:EntityData.

I am not sure about the inclusion of the rdfs and owl prefixes in there. Both if this is something that is desired, and if it is technically doable. Adding the full URIs might be better.

**Comment by hexmode** [comment]
> I am not sure about the inclusion of the rdfs and owl prefixes in there. Both if this is something that is desired, and if it is technically doable. Adding the full URIs might be better.

The Special:EntityData output is a mix.  The first item on [P15 on wikidata.org](view-source:https://www.wikidata.org/wiki/Special:EntityData/P15.ttl), for example, is
``` turtle
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix wikibase: <http://wikiba.se/ontology#> .
@prefix schema: <http://schema.org/> .
@prefix cc: <http://creativecommons.org/ns#> .
@prefix data: <https://www.wikidata.org/wiki/Special:EntityData/> .

data:P15 a schema:Dataset ;
	cc:license <http://creativecommons.org/publicdomain/zero/1.0/> ;
	wikibase:statements "21"^^xsd:integer .
```

(Note there is a `cc` prefix, but evidently none for the licenses (at least not included).)

So, URIs are probably ok, either way.

**Comment by hexmode** [comment]
> So, URIs are probably ok, either way.

It actually looks like wd can handle the URLs itself in some way.  Both `rdfs:` and `owl:` prefixes are defined in the [turtle for P15](https://www.wikidata.org/wiki/Special:EntityData/P15.ttl) but all urls are are spelled out completely in the [n-triples format](https://www.wikidata.org/wiki/Special:EntityData/P15.nt).

**Comment by JeroenDeDauw** [comment]
https://github.com/ProfessionalWiki/WikibaseRDF/discussions/34
